name: Deploy to VPS

on:
  push:
    branches:
      - main # <--- ¡IMPORTANTE! Cambia esto a la rama que usas para despliegue (ej. master, production)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VPS
      run: |
        # Conéctate a tu VPS y ejecuta los comandos de despliegue
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/eduardo-ssh/htdocs/cgm.salu.pro # <--- ¡CAMBIA ESTA RUTA POR LA RUTA ABSOLUTA DE TU APP EN EL VPS!
          git pull origin main
          npm install
          npm run build
          pm2 cgm-project
        EOF